2021-01-10 15:38:36,521 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:10:39,591 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:12:50,368 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:15:53,017 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:15:59,111 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:17:45,603 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:48:11,066 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
2021-01-10 16:50:18,186 ERROR: Exception on /reset_password_request [POST] [in /Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lyor/PycharmProjects/microblog_app/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
  File "/Users/lyor/PycharmProjects/microblog_app/app/email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt',
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/lyor/PycharmProjects/bot/microblog_app/lib/python3.9/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2021-01-10 16:52:27,284 INFO: Microblog startup [in /Users/lyor/PycharmProjects/microblog_app/app/__init__.py:47]
